ZenHub Enterprise 3 api documentation updates
ZenHubIO/API pull request #120
Opened 2021-04-12 21:21 UTC by cwarje

## What?

Updating documentation to accommodate changes made in ZenHub Enterprise 3

2021-04-12 21:24 UTC, EvHaus requested changes

2021-04-12 21:24 UTC, EvHaus commented on README.md
> +The ZenHub API root endpoint for Cloud is different than that of Enterprise and has also changed across Enterprise versions. Please refer to the table below for the appropriate endpoint.
Just want to make it super clear that this is ZenHub Enterprise, not GitHub Enterprise.

```suggestion
The ZenHub API root endpoint for Cloud is different than that of ZenHub On-Premise Enterprise instances and has also changed across Enterprise versions. Please refer to the table below for the appropriate endpoint.
```

2021-04-12 21:27 UTC, EvHaus approved these changes

2021-04-13 17:04 UTC, dylanmartyn approved these changes

2021-04-13 17:07 UTC, merged